# api-поддомен -> FastAPI
server {
    listen 80;
    server_name api.trip-ping.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.trip-ping.local;

    ssl_certificate     /etc/nginx/certs/tripping.crt;
    ssl_certificate_key /etc/nginx/certs/tripping.key;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $up http://fastapi:8000;
        proxy_pass         $up;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_read_timeout 86400;
    }
}
